{
    "openapi": "3.0.0",
    "info": {
        "title": "Marketplace Protocol",
        "description": "\r\nThe _Marketplace Protocol_ is a set of API requests and definitions to help you integrate external sellers into a VTEX marketplace as well as external marketplaces into VTEX sellers.\r\n\r\n## External Seller\r\n\r\nHere you will find the endpoints involved in the integration between a VTEX marketplace and an external seller. Note that some of these requests are typically sent by the seller while others are received.\r\n\r\n| **Request** | **From** | **To** |\r\n|-|-|-|\r\n| [Fulfillment simulation](https://developers.vtex.com/vtex-rest-api/reference/fulfillment-simulation) | Marketplace | Seller |\r\n| [Order placement](https://developers.vtex.com/vtex-rest-api/reference/order-placement) | Marketplace | Seller |\r\n| [Authorize fulfillment](https://developers.vtex.com/vtex-rest-api/reference/authorize-fulfillment) | Marketplace | Seller |\r\n| [Marketplace order cancellation](https://developers.vtex.com/vtex-rest-api/reference/marketplace-order-cancellation) | Marketplace | Seller |\r\n| [Send invoice](https://developers.vtex.com/vtex-rest-api/reference/send-invoice) | Seller | Marketplace |\r\n| [Send tracking information](https://developers.vtex.com/vtex-rest-api/reference/send-tracking-information) | Seller      | Marketplace |\r\n| [Update tracking status](https://developers.vtex.com/vtex-rest-api/reference/update-tracking-status) | Seller | Marketplace |\r\n| [Cancel order in marketplace](https://developers.vtex.com/vtex-rest-api/reference/cancel-order-in-marketplace) | Seller | Marketplace |\r\n\r\nFor a detailed explanation of the steps required to develop a custom connector to sell products from an external seller in your storefront, check out our complete [External Seller Integration Guide](https://developers.vtex.com/docs/guides/external-seller-integration-guide).\r\n\r\n\r\n## External Marketplace\r\n\r\nIn this section, you will find the endpoints involved in the VTEX integration between an external marketplace and a VTEX seller.\r\n\r\n\r\n| **Request** | **From** | **To** |\r\n|-|-|-|\r\n| [VTEX Mapper Registration](https://developers.vtex.com/vtex-rest-api/reference/vtex-mapper-registration) | External marketplace | VTEX system |\r\n| [Send Category Mapping to VTEX Mapper](https://developers.vtex.com/vtex-rest-api/reference/send-category-mapping-to-vtex-mapper) |  External marketplace | VTEX system |\r\n| [Authorize fulfillment](https://developers.vtex.com/vtex-rest-api/reference/authorize-fulfillment) | Marketplace | Seller |\r\n| [Place fulfillment order](https://developers.vtex.com/vtex-rest-api/reference/place-fulfillment-order)   | External marketplace | VTEX Seller |\r\n| [Authorize dispatch for fulfillment order](https://developers.vtex.com/vtex-rest-api/reference/authorize-dispatch-for-fulfillment-order) | External marketplace | VTEX Seller |\r\n\r\n\r\nFor a detailed explanation of the steps required to develop a custom connector to become an external marketplace for VTEX sellers, check out our complete [External Marketplace Integration Guide](https://developers.vtex.com/docs/guides/external-marketplace-integration-guide).",
        "contact": {},
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://{marketplaceServicesEndpoint}",
            "description": "Marketplace Service Endpoint",
            "variables": {
                "marketplaceServicesEndpoint": {
                    "description": "This is an endpoint sent from VTEX to the external seller in the [Order placement request](https://developers.vtex.com/vtex-rest-api/reference/external-seller#order-placement).",
                    "default": "{marketplaceServicesEndpoint}"
                }
            }
        }
    ],
    "paths": {
        "/pvt/orders/{marketplaceOrderId}/invoice": {
            "post": {
                "tags": [
                    "External Seller"
                ],
                "summary": "Send invoice",
                "description": "This request is sent by the external seller to the VTEX marketplace to send invoice information.\n\nThis can be necessary in a regular order or in the case of a return. The `type` field is used to indicate which of these is the case.",
                "operationId": "send-invoice",
                "parameters": [
                    {
                        "name": "marketplaceServicesEndpoint",
                        "in": "path",
                        "description": "This is an endpoint sent from VTEX to the external seller in the [Order placement request](https://developers.vtex.com/vtex-rest-api/reference/external-seller#order-placement).",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "marketplaceservicesendpoint.myvtex.com"
                        }
                    },
                    {
                        "name": "marketplaceOrderId",
                        "in": "path",
                        "description": "Identifies the order in the marketplace.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "1138342255777-01"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "type",
                                    "invoiceNumber",
                                    "items"
                                ],
                                "type": "object",
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "description": "Indicates the type of the invoice. Use `\"Output\"` for regular orders and `\"Input\"` for returns.",
                                        "example": "Output"
                                    },
                                    "invoiceNumber": {
                                        "type": "string",
                                        "description": "Invoice number",
                                        "example": "NFe-00002"
                                    },
                                    "courier": {
                                        "type": "string",
                                        "description": "Courier, if available on invoice.",
                                        "example": "courier-example"
                                    },
                                    "trackingNumber": {
                                        "type": "string",
                                        "description": "Tracking number.",
                                        "example": "12345678abc"
                                    },
                                    "trackingUrl": {
                                        "type": "string",
                                        "description": "Tracking URL.",
                                        "example": "https://courier-example.com/tracking"
                                    },
                                    "items": {
                                        "type": "array",
                                        "description": "Array containing the order items.",
                                        "items": {
                                            "type": "object",
                                            "description": "",
                                            "required": [
                                                "id",
                                                "quantity",
                                                "price"
                                            ],
                                            "properties": {
                                                "id": {
                                                    "type": "string",
                                                    "description": "SKU ID.",
                                                    "example": "6"
                                                },
                                                "quantity": {
                                                    "type": "integer",
                                                    "description": "Quantity of items of the SKU in the cart.",
                                                    "example": 1
                                                },
                                                "price": {
                                                    "type": "integer",
                                                    "description": "Price of the item.",
                                                    "example": 5500
                                                }
                                            }
                                        }
                                    },
                                    "issuanceDate": {
                                        "type": "string",
                                        "description": "Issuance date.",
                                        "example": "2021-05-21T10:00:00"
                                    },
                                    "invoiceValue": {
                                        "type": "integer",
                                        "description": "Invoice value.",
                                        "example": 6000
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "content": {
                            "application/json": {
                                "examples": {
                                    "response": {
                                        "value": {
                                            "date": "2021-06-09T15:22:56.7612218-02:00",
                                            "orderId": "1138342255777-01",
                                            "receipt": "527b1ae251264ef1b7a9b597cd8f16b9"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/pvt/orders/{marketplaceOrderId}/invoice/{invoiceNumber}": {
            "post": {
                "tags": [
                    "External Seller"
                ],
                "summary": "Send tracking information",
                "description": "This request is sent by the external seller to the VTEX marketplace to add tracking information to a given order's invoice, in case it is necessary to do so after the invoice has been sent.",
                "operationId": "send-tracking-information",
                "parameters": [
                    {
                        "name": "marketplaceServicesEndpoint",
                        "in": "path",
                        "description": "This is an endpoint sent from VTEX to the external seller in the [Order placement request](https://developers.vtex.com/vtex-rest-api/reference/external-seller#order-placement).",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "marketplaceservicesendpoint.myvtex.com"
                        }
                    },
                    {
                        "name": "marketplaceOrderId",
                        "in": "path",
                        "description": "Identifies the order in the marketplace.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "1138342255777-01"
                        }
                    },
                    {
                        "name": "invoiceNumber",
                        "in": "path",
                        "description": "Invoice number.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "NFe-00002"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "courier": {
                                        "type": "string",
                                        "description": "Courier.",
                                        "example": "courier-example"
                                    },
                                    "trackingNumber": {
                                        "type": "string",
                                        "description": "Tracking number.",
                                        "example": "12345678abc"
                                    },
                                    "trackingUrl": {
                                        "type": "string",
                                        "description": "Tracking URL.",
                                        "example": "https://courier-example.com/tracking"
                                    },
                                    "dispatchedDate": {
                                        "type": "string",
                                        "description": "Date of order dispatch.",
                                        "example": "2021-06-09"
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "content": {
                            "application/json": {
                                "examples": {
                                    "response": {
                                        "value": {
                                            "date": "2021-06-09T15:22:56.7612218-02:00",
                                            "orderId": "1138342255777-01",
                                            "receipt": "527b1ae251264ef1b7a9b597cd8f16b9"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/pvt/orders/{marketplaceOrderId}/invoice/{invoiceNumber}/tracking": {
            "post": {
                "tags": [
                    "External Seller"
                ],
                "summary": "Update tracking status",
                "description": "This request is sent by the external seller to the VTEX marketplace to update a given order's tracking status.",
                "operationId": "update-tracking-status",
                "parameters": [
                    {
                        "name": "marketplaceServicesEndpoint",
                        "in": "path",
                        "description": "This is an endpoint sent from VTEX to the external seller in the [Order placement request](https://developers.vtex.com/vtex-rest-api/reference/external-seller#order-placement).",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "marketplaceservicesendpoint.myvtex.com"
                        }
                    },
                    {
                        "name": "marketplaceOrderId",
                        "in": "path",
                        "description": "Identifies the order in the marketplace.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "1138342255777-01"
                        }
                    },
                    {
                        "name": "invoiceNumber",
                        "in": "path",
                        "description": "Invoice number.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "NFe-00002"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": [
                                    "isDelivered"
                                ],
                                "properties": {
                                    "isDelivered": {
                                        "type": "boolean",
                                        "description": "Indicates if order has been delivered. `false` if it is in transit.",
                                        "example": true
                                    },
                                    "events": {
                                        "type": "array",
                                        "description": "Array containing information on each tracking event received.",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "city": {
                                                    "type": "string",
                                                    "description": "City where the event ocurred.",
                                                    "example": "Rio de Janeiro"
                                                },
                                                "state": {
                                                    "type": "string",
                                                    "description": "State where the event ocurred.",
                                                    "example": "Rio de Janeiro"
                                                },
                                                "description": {
                                                    "type": "string",
                                                    "description": "Description of the event.",
                                                    "example": "Order delivered."
                                                },
                                                "date": {
                                                    "type": "string",
                                                    "description": "Date when event ocurred.",
                                                    "example": "2021-03-16"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "content": {
                            "application/json": {
                                "examples": {
                                    "response": {
                                        "value": {
                                            "date": "2021-06-09T15:22:56.7612218-02:00",
                                            "orderId": "1138342255777-01",
                                            "receipt": "527b1ae251264ef1b7a9b597cd8f16b9"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/pvt/orders/{marketplaceOrderId}/cancel": {
            "post": {
                "tags": [
                    "External Seller"
                ],
                "summary": "Cancel order in marketplace",
                "description": "This request is sent by the external seller to the VTEX marketplace to cancel an order.",
                "operationId": "cancel-order-in-marketplace",
                "parameters": [
                    {
                        "name": "marketplaceServicesEndpoint",
                        "in": "path",
                        "description": "This is an endpoint sent from VTEX to the external seller in the [Order placement request](https://developers.vtex.com/vtex-rest-api/reference/external-seller#order-placement).",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "marketplaceservicesendpoint.myvtex.com"
                        }
                    },
                    {
                        "name": "marketplaceOrderId",
                        "in": "path",
                        "description": "Identifies the order in the marketplace.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "1138342255777-01"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": [
                                    "reason"
                                ],
                                "properties": {
                                    "reason": {
                                        "type": "string",
                                        "description": "Insert here the reason for the order's cancellation.",
                                        "example": "Product is unavailable"
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "content": {
                            "application/json": {
                                "examples": {
                                    "response": {
                                        "value": {
                                            "date": "2021-06-09T15:22:56.7612218-02:00",
                                            "orderId": "1138342255777-01",
                                            "receipt": "527b1ae251264ef1b7a9b597cd8f16b9"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        }
    },
    "security": [
        {
            "appKey": [],
            "appToken": []
        }
    ],
    "components": {
        "securitySchemes": {
            "appKey": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppKey"
            },
            "appToken": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppToken"
            }
        }
    },
    "tags": [
        {
            "name": "External Seller"
        }
    ]
}
